medibloc/panacea-core

Jenkinsfile
app/app.go
app/export.go
cmd/panaceacli/main.go
go.mod
go.sum
x/did/alias.go
x/did/client/cli/query.go
x/did/client/cli/tx.go
x/did/client/module_client.go
x/did/handler.go
x/did/keeper.go
x/did/keeper_keys.go
x/did/querier.go
x/did/types/codec.go
x/did/types/did.go
x/did/types/errors.go
x/did/types/keys.go
x/did/types/msgs.go

**NOTE:**
I didn't create a `dev` branch. All PRs would be based on `master` (aka. [trunk-based approach](https://www.toptal.com/software/trunk-based-development-git-flow) that the `master` is always a source-of-truth). It means that all PRs must be reliable.
- A new feature for creating/resolving/updating DIDs
- Manually done by a new CLI command.
```
~ ❯❯❯ panaceacli tx did create-did --chain-id=testing --from=panacea1zyfxqj425wf5zzquagyqden5xekhd94srrxuh5
{"chain_id":"testing","account_number":"0","sequence":"3","fee":{"amount":null,"gas":"200000"},"msgs":[{"type":"did/MsgCreateDID","value":{"did":"did:panacea:testnet:LPSAj6BKigRM8t4vAqT11","document":{"id":"did:panacea:testnet:LPSAj6BKigRM8t4vAqT11","publicKey":[{"id":"key1","type":"Secp256k1VerificationKey","publicKeyBase58":"oe1oi7s4 …
```

create/resolve/update DIDs

---

Dockerfile
Makefile
go.mod
go.sum
x/did/client/cli/query.go
x/did/client/cli/tx.go
x/did/client/keystore/keystore.go
x/did/client/keystore/keystore_test.go
x/did/handler.go
x/did/types/did.go
x/did/types/did_test.go
x/did/types/errors.go
x/did/types/msgs.go

Close #17 
Whenever DID is created, the private key should be stored securely on disk, so that it can be reusable.
I've implemented the `x/did/client/keystore` package by generalizing the [Web3 Secret Storage Definition](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) which is defined by Ethereum.
The keystore can be used for any type of private keys, such as blockchain account or DID.
I didn't use the Leveldb which is used by `panaceacli` internally, because it's tightly coupled with the blockchain account concept and it's not compatible with other programming languages.
A private key is stored like below. Note that the `address` is used for the DID key ID (`did#key-x`). The `address` can be anything you want.
```
$ cat …
```

Implement DID keystore

---

go.mod
x/did/client/cli/tx.go

Close #21 
If the option `--use-mnemonic` is specified, the CLI accepts a BIP39 mnemonic and a passphrase.
```
~ ❯❯❯ docker exec -it testing1 panaceacli tx did create-did testnet --use-mnemonic --chain-id=testing --from=panacea1ee4adg8uk26tllsu5yu3x8v9lz2xur0lvl6qy7                                                                                              ✘ 1
> Enter your BIP39 mnemonic, or hit enter to generate one:
A random mnemonic was generated: exotic suspect harsh hungry believe saddle cup nose master consider little senior thing recall hood glare same lemon lion arrest thrive depth uphold razor
Enter your BIP39 passphrase:
Repeat the password:
{"chain_id":"testing","account_number":"0","sequence":"1","fee":{"amount":null,"gas":"200000"},"msgs":[{"type":"did/MsgCreateDID","value":{ …
```

Add an option for using BIP39 mnemonic to create DID

---

.gitignore
Dockerfile
Jenkinsfile
Makefile

See http://ci.medibloc.org/job/panacea-core/job/PR-32/. You can find the `Code Coverage` menu on the left side-bar.
Also, in `Dockerfile`, download the pre-built `golangci-lint`, instead of `go get .../golangci-lint` everytime.

CI: add code-coverage and make the 'lint' stage faster

---

.github/workflows/ci.yml
.github/workflows/go.yml
Makefile

For experimental purposes, let's use Github Actions along with Jenkins for a while.
All good, except publishing the code coverage report...
There is no way to publish HTML reports as Jenkins supports. Many people are using proprietary coverage report services, such as Coverall. But, I don't want to pay for it. 
As work-around, I defined the following steps.
1. Convert `coverage.out` into `coverage.lcov`
2. Post a comment about the summary of `coverage.lcov`. You can find comments below.
3. Upload `coverage.html` as an artifact of Github Actions Job. You can find the artifact on this [link](https://github.com/medibloc/panacea-core/pull/33/checks?check_run_id=1034513451) (on the right side).

Enable Github Actions

---

x/did/client/cli/query.go
x/did/client/cli/tx.go
x/did/handler.go
x/did/handler_test.go
x/did/keeper.go
x/did/types/msgs.go
x/did/types/msgs_test.go

Based on #29 
Previously `MsgCreateDID` didn't have any signature and verification logic. It can cause that someone who doesn't know the DID private key can create a DID document.
To solve it, `MsgCreateDID` should have the signature, similar as `MsgUpdateDID`.

Add signature verification for CreateDID

---

.github/workflows/ci.yml
x/did/alias.go
x/did/client/cli/query.go
x/did/client/cli/tx.go
x/did/client/module_client.go
x/did/genesis_test.go
x/did/handler.go
x/did/handler_test.go
x/did/keeper.go
x/did/types/auth.go
x/did/types/auth_test.go
x/did/types/codec.go
x/did/types/did.go
x/did/types/did_test.go
x/did/types/errors.go
x/did/types/msgs.go
x/did/types/msgs_test.go

Based on #34 
According to the [DID spec](https://www.w3.org/TR/did-core/#did-syntax):
```
A DID is expected to be persistent and immutable. That is, a DID is bound exclusively and permanently to its one and only subject. Even after a DID is deactivated, it is intended that it never be repurposed.
```
DID shouldn't be deleted from Keeper. It should be just deactivated, so that anyone cannot recreate it.
This topic also has been discussed in [#29](https://github.com/medibloc/panacea-core/pull/29#issuecomment-684121150).

Deactivate DID instead of deleting it

---

x/did/client/cli/query.go
x/did/client/cli/tx.go
x/did/types/did.go
x/did/types/did_test.go
x/did/types/msgs_test.go

The format of DID KeyID is:
```
did#name
```
like `did:panacea:testnet:KS5zGZt66Me8MCctZBYrP#key1`.
Here, the prefix (the DID part) must match with the DID (eg. `did:panacea:testnet:KS5zGZt66Me8MCctZBYrP`).
Also, the suffix (`#key1`) must not have whitespaces.

Check if the prefix of the DID KeyID matches with the DID

---

docs/did.md
x/did/types/did.go
x/did/types/did_test.go
x/did/types/msgs_test.go

- Add `@context`
- Support the embedded DID public key in the `authentication`: [link](https://www.w3.org/TR/did-core/#example-18-authentication-property-containing-three-verification-methods)
TODO: other enhancements in #43

Add DID `@context` and Extend `authentication`

---

docs/did.md
x/did/client/cli/tx.go
x/did/client/cli/tx_test.go
x/did/handler.go
x/did/handler_test.go
x/did/types/did.go
x/did/types/did_test.go
x/did/types/errors.go
x/did/types/msgs.go
x/did/types/msgs_test.go

- On 2020-09-07, the terminology `publicKey` was changed to `verificationMethod` by W3C.
- Each `verificationMethod` must have a `controller`: [link](https://www.w3.org/TR/did-core/#verification-methods)
```
The properties MUST include the id, type, controller
```
- Currently, I put a limitation that the `controller` must be always the same as the [DID Subject](https://www.w3.org/TR/did-core/#dfn-did-subjectshttps://www.w3.org/TR/did-core/#dfn-did-subjects), because we have never defined how to handle other DID controllers (different from the DID Subject).
TODO:
Support other DID controllers: https://www.w3.org/TR/did-core/#example-13-various-public-keys

Use DID `verificationMethod` terminology and Add the method `controller`

---

x/did/types/did.go
x/did/types/did_test.go

it's worth to define the max length of the verification method suffix as 128bytes, because the value is used for the keystore filename. (The max length of linux filenames is usually 256bytes).
The keystore filename consists of:
```
UTC--2006-01-02T15-04-05.000000000Z--did:panacea:mainnet:aaaaaaaaaaaaaaaaaaaaaa#SUFFIX.json
```
If `SUFFIX` is 128bytes, the total length is 213bytes (< 256bytes).

Limit the length of the DID verification method ID suffix

---

init/gentx.go

This is a known issue fixed by https://github.com/cosmos/cosmos-sdk/pull/6021 (cosmos-sdk v0.37.11).
Because of this bug, we cannot run `panacead gentx` (https://github.com/medibloc/panacea-core/pull/54#issuecomment-696467010).
Before merging #58, let's use this temporary fix, so that `panacead gentx` can be succeeded.
If #58 is merged first, close this PR without merging.

Fix failed gentx because node is untrusted

---

cmd/panacead/main.go
go.mod
go.sum

Closes #60 
This will be released as `v1.2.6-internal`.
Tests:
```
$ panacead start --halt-height 30
...
I[2020-10-13|18:00:14.889] Executed block                               module=state height=30 validTxs=0 invalidTxs=0
I[2020-10-13|18:00:14.893] halting node per configuration               module=main height=30
```

Add a new option: halt-height

---

x/did/types/genesis.go

Previously, the `genesis.json` looked like:
```json
{
"app_state": {
"did": {
"Documents": {
}
}
}
```
Let's use `documents` instead of `Documents`.
```json
```json
{
"app_state": {
"did": {
"documents": {
"did:panacea:9iofqBjmEkL4XRiCguNxun3GVKn2Ghoqud39uS25S1aY": {
}
}
}
}
```

Use 'documents' as the DID genesis JSON key, instead of 'Documents'

---

x/aol/client/rest/query.go
x/did/client/rest/query.go

Close #72 
This version was already deployed on the Testnet for Medipass (only `panaceacli`, not `panacead`).
After merging this PR, I'm gonna release v1.3.2 and deploy it.

Fix: Make LCD use the latest height or the height specified in the URL query

---

x/did/client/rest/query.go

Fix #71 
```
(⎈ |N/A:N/A)~ ❯❯❯ curl -v localhost:1317/api/v1/did/did:panacea:7Prd74ry1Uct87nZqL3ny7aR7Cg46JamVbJgk8azVgUm | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    25  100    25    0     0   8333      0 --:--:-- --:--:-- --:--:--  8333
...
< HTTP/1.1 404 Not Found
...
{
"error": "DID not found"
}
(⎈ |N/A:N/A)~ ❯❯❯ curl -v localhost:1317/api/v1/did/did:panacea:3YzwQVAXWqe6Tb7wApG98itdjjdEKKTqVdiKeHxAFD7Z | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    35  100    35    0     0  17500      0 --:--:-- --:--:-- --:--:-- 17500
...
< HTTP/1.1 404 Not Found
...
{
"error": "DID already deactivated"
}
```
CLI has worked …

Return 404 when DID is not found or deactivated

---

docs/did.md

My [PR](https://github.com/w3c/did-spec-registries/pull/150) to the W3C DID spec registry was not approved, because I didn't put the privacy consideration to the DID spec.

Add privacy considerations to the DID spec

---

.github/workflows/ci.yml

Previously, The `golangci-lint` github action has a problem. So, I've run it as a separate github action job. 
But, it has been failed from today for some reason.
I just bumped its version from v1 to v2, and moved it to the origin github action job. Now it works.

Fix Lint CI

---

x/aol/keeper.go
x/aol/keeper_keys.go
x/aol/keeper_keys_test.go

Similar as the PR #75 , but based on the `v1.2.6-internal`, because this fix is essential for upgrading from `v1.2.x` to `v1.3.x`.
This fix would be released as `v1.2.7-internal`.

For 1.2.7-internal: Fix parsing keeper keys of `x/aol`

---

x/aol/keeper.go
x/aol/keeper_keys.go
x/aol/keeper_keys_test.go

Similar as the PR #82  , but based on the `v1.2.6` instead of `v1.2.6-internal`.
This fix would be released as `v1.2.7`.

For 1.2.7: Fix parsing keeper keys of `x/aol`

---

CHANGELOG.md
app/app.go
x/token/keeper/keeper.go
x/token/types/expected_keepers.go

Fixes #93 
No unit test yet. Unit tests will be added soon by following the Cosmos-SDK's way (probably in the newer Cosmos version).
A manual test was done:
```bash
panacead export --for-zero-height --height=10
```
```json
"supply": {
"supply": [
{
"amount": "1000000000",
"denom": "ulov221"
},
{
"amount": "100000001584400",
"denom": "umed"
}
]
},
"token": {
"tokens": {
"LOV-221": {
"mintable": false,
"name": "love",
"owner_address": "panacea1xs5e3p3jxfxr3n9xluagkgnxxk9vpcm0dcrew2",
"symbol": "LOV-221",
"total_supply": {
"amount": "1000000000",
"denom": "ulov221"
}
}
}
}
```

x/token: Fix to update the total supply of all coins when issuing new tokens

---

x/did/client/cli/tx.go
x/did/client/cli/tx_test.go
x/did/handler.go
x/did/handler_test.go
x/did/keeper/genesis_test.go
x/did/types/did.go
x/did/types/did_test.go
x/did/types/errors.go
x/did/types/msgs.go
x/did/types/msgs_test.go

Closes #48 
- Now, DID Document can contain (according to [the semi-finalized new DID spec](https://www.w3.org/TR/did-core/))
- `controller`
- `service`
- `assertionMethod`: essential for VC/VP verification using the [vc-service](https://github.com/medibloc/vc-service)
- `keyAgreement`
- `capabilityInvocation`
- `capabilityDelegation`

x/did: Support service / controller / various verificationRelationship in DID Document

---

x/did/handler.go
x/did/types/did.go
x/did/types/did_test.go

Previously, the role of `VerificationMethodByID(id)` was:
- Find a `authentication` from the DID Document
- Find a corresponding `verificationMethod` which has the same ID as the `authentication`.
It was used for the `DIDDocument.Valid()`. But, if the DID Document has `assertionMethod`s, not `authentication`s, the `VerificationMethodByID(id)` returns 'not found'.
```json
{
"verificationMethod": [{
"id": "key1",
"publicKeyBase58": "asdgkadjspoiejflkadskjfa",
}],
"assertionMethod": [
"key1"
]
}
```
So, the function should be split for various use cases.
- `VerificationMethodByID(id)`
- Find a `verificationMethod` by its ID from the DID Document
- `VerificationMethodFrom(verificationRelationships, ID)`
- Find a `verificationRelationship` from the DID Document
- Find a corresponding …

x/did: Fix checking if VerificationRelationships are valid

---

Makefile
app/prefix.go
cmd/panacead/cmd/root.go
x/panacea/client/rest/rest.go

From Stargate, we will have only one binary: `panacead`.
CI should work from this PR.

starport: Change Makefile to build only `panacead`

---

.gitbook/guide/interaction-with-the-network-cli.md

- Fixed wrong option descriptions of the `create-validator` CLI command.
- Add a new guide for the `edit-validator` CLI command.

docs: Fix `create-validator` guide and Add `edit-validator` guide

---

protodep.lock
protodep.toml

So far, we've used the only `cosmos/base/query/v1beta1/pagniation.proto`. But, we need to use other `cosmos/base/**/*.proto` files, such as `cosmos/base/v1beta1/coin.proto`.
Thus, let's fetch all of `cosmos/base/**/*.proto` files as dependencies. Later, we can minimize them.

feat: stargate: Add more cosmos/base proto dependencies

---

cmd/panacead/cmd/init.go
cmd/panacead/cmd/root.go
types/assets/assets.go

When running `panacead init ...`, the Cosmos generates a genesis with default params that are defined in each `x/*` modules (`stake` coin denom, and so on...).
So, it's annoying to modify the generated `genesis.json` every time after running `panacead init ...`.
Thus, let's override it.
Actually, we've had this overriding logic so far: https://github.com/medibloc/panacea-core/blob/985271f795c2ff0bf1f6b63152d97fabb41dbfa2/init/init.go
In this PR, I made it work in Stargate by referring to https://github.com/public-awesome/stargaze/blob/b92bf9847559b9c7f4ac08576d056d3d00efe12c/cmd/starsd/cmd/init.go.

feat: stargate: Add the default genesis overriding

---

.gitbook/guide/deploy-a-testnet.md

As we usually run a local node for testing Stargate manually, I just updated a `Deploy a Testnet` doc.
Other doc must be updated after the Stargate development is done.

docs: stargate: Update the `deploy-a-testnet` doc for Stargate

---

go.mod
x/token/types/errors.go
x/token/types/types.go
x/token/types/types_test.go

Just added simple tests that check `Token` type validation logics.
TODO:
- Test keeper, handler, and so on (by following [Cosmos' idea](https://github.com/cosmos/cosmos-sdk/blob/d7c5bc5f35505e1d64e9b3521067871947d55bfa/x/bank/keeper/keeper_test.go#L67), I guess)

feat: stargate: Add unit tests for `token`-related types

---

go.mod
proto/token/genesis.proto
x/token/genesis.go
x/token/types/errors.go
x/token/types/genesis.go
x/token/types/genesis.pb.go
x/token/types/types.go
x/token/types/types_test.go

Because the previous Panacea exports a `genesis.json` like below, the new Panacea should be able to read/parse it properly:
```json
{
"app_state": {
"token": {                                                                                                                          
"tokens": {                                                                                                                       
"LOV-205": {                                                                                                                    
"mintable": false,                                                                                                            
"name": "love", …
```

fix: stargate: Make the `token` genesis backward-compatible

---

x/aol/client/cli/txWriter.go

Parameters have been passed in incorrect order.

fix: stargate: Fix callers of NewMsgAddWriter

---

x/aol/client/cli/txRecord.go

How to sign with multi-signers is already described in the [Cosmos SDK doc](https://docs.cosmos.network/v0.42/run-node/txs.html#signing-a-transaction-2).
But, Cosmos SDK doesn't provide an all-in-one function for it.
Thus, I implemented it.
I tested it manually using `panacead tx aol add-record ...` for now, since it's not simple to write unit tests due to Keyring and Panacea daemon. But, I'll try to write tests somehow soon.

fix: stargate: Support multi-signers in CLI (for `tx aol add-record`)

---

.golangci.yml
go.mod
go.sum
protodep.lock
protodep.toml

feat: stargate: Bump cosmos-sdk to v0.42.6

---

.github/workflows/docker-publish.yml
Dockerfile

When master branch changed and add new tag then build docker image and publish git package.
There were a few things to consider.
- Required of wasmvm module `libwasmvm.so` library 
- docker image build and publish([link](https://github.com/docker/build-push-action))

feat: Add git flow to make docker image

---

proto/panacea/aol/v2/genesis.proto
proto/panacea/aol/v2/owner.proto
proto/panacea/aol/v2/query.proto
proto/panacea/aol/v2/record.proto
proto/panacea/aol/v2/topic.proto
proto/panacea/aol/v2/tx.proto
proto/panacea/aol/v2/writer.proto
proto/panacea/burn/v2/genesis.proto
proto/panacea/burn/v2/query.proto
proto/panacea/did/v2/did.proto
proto/panacea/did/v2/genesis.proto
proto/panacea/did/v2/query.proto
proto/panacea/did/v2/tx.proto
proto/panacea/token/v2/genesis.proto
proto/panacea/token/v2/query.proto
proto/panacea/token/v2/token.proto
proto/panacea/token/v2/tx.proto

Simply added setting `java_multiple_files = true;` to proto file.

feat: Add java_multiple_files option in proto files

---

.github/workflows/docker-publish.yml

The `Docker` Github Actions should be started only after the `ci` Actions is completed, because it doesn't make sense to publish a Docker image that doesn't pass the CI.
Reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run

chore: Run docker-publish Github Actions only after the CI is completed

---

x/did/keeper/grpc_query_did.go
x/token/keeper/grpc_query_token.go

```
┌──────────────┐
│ HTTP caller  │
└──────────────┘
▲
│
│
┌─────────────────────────────────────────────────┼──────────────────┐
│                                                 │                  │
│ Cosmos SDK                                      │                  │
│                                                 │                  │
│                                                 │HTTP status code  │
│                                       ┌─────────┴─────────┐        │
│                                       │  gRPC Gateway     │        │
│                                       └───────────────────┘        │
│                                                 ▲                  │
│                                                 │ gRPC error code  │
│ …
```

fix: Return gRPC status code from `grpc_query_*.go` in `x/did` and `x/token`

---

CHANGELOG.md

Some important changes on `x/did` have been missed in the CHANGELOG.
Also, I added module name prefixes as below (by following the convention of the [cosmos-sdk changelog](https://github.com/cosmos/cosmos-sdk/blob/master/CHANGELOG.md)):
```
(x/did) #123 Something
```

docs: Add missing changes to CHANGELOG

---

CHANGELOG.md
app/app.go
go.mod
go.sum

I'm bumping the cosmos-sdk from v0.42.7 to v0.42.9.
The [v0.42.8](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.8) doesn't have critical fixes, but the [v0.42.9](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.9) contains a [critical bug fix](https://github.com/cosmos/cosmos-sdk/issues/9800) with regard to IBC. Without that, it seems that it's not possible to start IBC channels (I'm not familiar with IBC yet).
The v0.42.9 requires to update an app module manager by adding `x/capability` module to Begin Blockers.
So, I referred to the [cosmos/gaia](https://github.com/cosmos/gaia/commit/1b810239668c98efcc717c1d75be176233e57d02) for that.
TODO: Test whether we can upgrade the `panacead` without hard-forking.

fix: Bump cosmos-sdk to v0.42.9

---

README.md

I removed URLs of the explorer and the wallet, because the explorer URL has been already posted in each 'network' repo.

docs: Update URL links in README

---

.gitbook/guide/join-the-network.md

I have created a document that can modify the validator's description.

docs: add a guide to apply the validator's descrption

---

Dockerfile

Modify Dockerfile for Cosmwasm static linking.
The binary file for panacea `panacead' works well in Linux OS such as ubuntu or alpine.

fix: Modify Dockerfile for Cosmwasm static linking

---

.gitbook/guide/interaction-with-the-network-cli.md
.gitbook/guide/join-the-network.md

Although we already added a `edit-validator` guide to the `join-the-network.md` (PR https://github.com/medibloc/panacea-core/pull/248), I just found that the `interaction-with-the-network-cli.md` has already had the `edit-validator` guide.
To avoid splitting information, I merged all `edit-validator` guides into the `interaction-with-the-network-cli.md` . Instead, I put only links in the `join-the-network.md`.

docs: merge split documents for `edit-validator`

---

x/market/client/cli/parse.go
x/market/client/cli/tx.go
x/market/client/cli/txDeal.go
x/market/client/cli/txDeal_test.go
x/market/keeper/deal.go
x/market/keeper/deal_test.go
x/market/keeper/msg_server_deal.go
x/market/types/codec.go
x/market/types/errors.go
x/market/types/message_deal.go

What I done
- Build Tx Command-Line for ```SellData```.
- Apply Verification for DataValidator Signature for ```SellData```.
- Register ```MsgSellData``` in ```types/codec.go```.
TODO
- Replace ```max_num_data``` field and ```cur_num_data``` field with pricePerData.

feat: Apply Signature Verification for SellData and Build Tx Command-Line

---

x/datapool/client/cli/tx.go
x/datapool/client/cli/txPool.go
x/datapool/types/message_pool.go

- Command-Line Interface(CLI) for Register Data Validator.
- Add `CmdRegisterDataValidator` and modify `ValidateBasic` function.

feat: Command Line for Register Data Validator

---

.gitbook/SUMMARY.md

At the PR #289, It's my bad that I forgot to add the new roadmap page to the ToC (table of contents) of Gitbook. That's why the `Roadmap` button is not displayed in the left sidebar of https://medibloc.gitbook.io/panacea-core/.

docs: add roadmap to gitbook ToC

---

.github/workflows/ci.yml

All the github actions fail in golangci-lint step with error of `error: buildir: failed to load package goarch: could not load export data`. I found the [same issue](https://github.com/golangci/golangci-lint-action/issues/434) we've encountered. They said they removed the installation of go step at all, so do upgrade to v3.

ci: upgrade golangci-lint version

---

x/datapool/client/cli/query.go
x/datapool/client/cli/queryPool.go
x/datapool/keeper/grpc_query_pool.go
x/datapool/keeper/grpc_query_pool_test.go
x/datapool/keeper/pool.go
x/datapool/keeper/pool_test.go
x/datapool/types/errors.go

Added a function to query the pool.

feat: added query pool 

---

proto/panacea/datapool/v2/query.proto
x/datapool/README.md
x/datapool/client/cli/query.go
x/datapool/client/cli/queryParams.go
x/datapool/keeper/grpc_query_pool.go
x/datapool/keeper/grpc_query_pool_test.go
x/datapool/types/query.pb.go
x/datapool/types/query.pb.gw.go

Implemented query params of datapool module. 
It may be used to get NFT contract address registered on `x/datapool` module

feat: add query params of datapool module

---

app/app.go
types/testsuite/suite.go
x/datapool/keeper/pool.go
x/datapool/keeper/pool_test.go
x/datapool/types/errors.go
x/datapool/types/expected_keepers.go

This function uses `BankKeeper` directly without using the `x/token` module.
Because I know that `x/module` is deprecated.
When data is sold, `shareToken` is minted and sent to the seller.

feat: added ability mint shareToken

---

.gitbook/overview/roadmap.md

I found `data market protocol` remained, so changed it.

docs: remained data market -> data exchange

---

x/datadeal/client/cli/queryDeal.go
x/datadeal/client/cli/testdata/create_deal_file.json
x/datadeal/client/cli/txDeal.go
x/datadeal/keeper/deal.go
x/datadeal/types/deal.go
x/datadeal/types/genesis.go

- Change parameter name based on cosmos-sdk convention.
- Apply `gofmt` to some code.
- Fix typo in deal model

chore: Fix typo and refactor parameter name in Deal model.

---

app/app.go
go.mod

We ran into an error situation during the Testnet deployment.
```
Jun 10 03:09:17 testnet-sentry panacead[3707341]: panic: cannot delete latest saved version (12)
Jun 10 03:09:17 testnet-sentry panacead[3707341]: goroutine 1 [running]:
Jun 10 03:09:17 testnet-sentry panacead[3707341]: github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc0001cc460)
Jun 10 03:09:17 testnet-sentry panacead[3707341]:         /home/ubuntu/go/pkg/mod/github.com/medibloc/cosmos-sdk@v0.42.11-panacea.1/store/rootmulti/store.go:388 +0x26e
```
This error occurs when the following code is excuted.
https://github.com/cosmos/cosmos-sdk/blob/v0.42.11/store/rootmulti/store.go#L380
CosmosHub has solved this related problem as follows.
https://github.com/cosmos/gaia/blob/v5.0.8/app/app.go#L428
We also …

feat: fix upgradeHander issue

---

client/decrypt/decrypt.go
cmd/panacead/cmd/root.go
go.mod

Closes #354 
The following features have been added.
* Added `panacead decrypt (--text {cipherText} | --path {cipherText file path}
* You can decrypt the encrypted text with the ECDSA-based publicKey using the privateKey stored in your local store.

feat: added cipher text decrypt function

---

Dockerfile

Currently, github action of `build and push docker image` is failed.
I missed Dockerfile when upgrading cosmwasm version, so I updated.

fix: update Dockerfile for wasmvm v1.0.0-beta7

---

x/oracle/keeper/keeper.go
x/oracle/keeper/keeper_test.go
x/oracle/types/keys.go

* Added queue to get list of `OracleRegistrationVotes` that have closed voting.
* Only data whose time passed by the key is retrieved.
Reference link: https://github.com/cosmos/cosmos-sdk/blob/main/x/gov/keeper/keeper.go#L203

feat: add oracle registration vote queue

---

x/datadeal/genesis.go
x/datadeal/types/genesis.go

Current version of panacea cannot be initiated and started because panic occurs in validating and initiating the genesis of `datadeal` module. So I just commented them.

chore: comment implement panic

---

x/oracle/keeper/oracle.go
x/oracle/keeper/oracle_test.go
x/oracle/types/errors.go

A validator, who can apply to be an oracle, could repeatedly request oracle registration regardless of the voting result. It results in the emission of event repeatedly to other oracles, and makes other oracles vote redundantly.
Thus, oracle registration vote can be opened only in the following cases.
- When applying for registration for the first time (not stored in `OracleRegistration` kv store)
- Applied but the previous vote is rejected (`OracleRegistration.Status` == `REJECTED`)
- When a registered oracle want to be shared the oracle private key again (e.g. delete `oracle_priv_key.sealed`) (`OracleRegistration.Status` == `PASSED` && `Oracle.Status` == `JAILED`)

fix: oracle registration status check of RegisterOracle

---

x/oracle/client/cli/txRegisterOracle.go
x/oracle/types/message_oracle.go

I added a missing field to the `NewMsgRegisterOracle` function.

feat: add nonce parameter in newMsgRegisterOracle func

---

.github/workflows/ci.yml

As the Lint job usually takes minutes, let's separate it with the main CI job, so that we can see the lint result quickly.

ci: separate the Lint job with the main job

---

x/datadeal/client/cli/tx.go
x/datadeal/client/cli/txDeactivateDeal.go
x/datadeal/keeper/deal.go
x/datadeal/keeper/deal_test.go
x/datadeal/keeper/msg_server_deal.go
x/datadeal/types/errors.go
x/datadeal/types/message_deal.go

Closes #420 
- Implement Deactivate Deal keeper, Tx CLI, and test code for keeper function.
- Marked as a `TODO` that when after deactivating a deal, the DataVerification/Delivery vote queue will be removed after #449 merged.

feat: add DeactivateDeal keeper and Tx CLI

---

app/app.go

In current main branch, there are duplicated codes for oracle module.
When I try to init and start chain, I got an error like below.
`panic: Potential key collision between KVStores:oracle - oracle`

fix: remove duplicated oracle in app.go

---

cmd/panacead/cmd/encrypt_data.go

`encrypt-data` CLI returns encrypted data encoded using base64, which can be used to request for data validation.

fix: add base64 encoding in data encryption

---

x/oracle/keeper/oracle_test.go
x/oracle/types/oracle.go

fix: OracleCommissionRate upper limit

---

cmd/panacead/cmd/decrypt_data.go

related: #554 
When outputting the `decrypt-data` cmd we need to change the type byte array to string.

fix: Change byte array to string when decypt-data cli output logs

---

x/datadeal/keeper/deal.go

close #572 
We should refund the remaining amount of the deal instead of the budget.
And I will add test code. 
But it need to refactorying `deal_test.go`, `certificate_test.go`

fix: refunds for invalid deactivation deal

---

x/datadeal/genesis.go
x/datadeal/genesis_test.go
x/datadeal/keeper/consent.go
x/datadeal/keeper/consent_test.go
x/datadeal/types/genesis.go

Add a genesis function of Consent
- Also, add a test code of `InitGenesis` and `ExportGenesis`.

feat: add a genesis function of Consent

---

.gitbook/guide/interaction-with-the-network-cli.md

Since we updated the cosmos sdk dependency, the CLI usage for multisig has been changed. Please see details from diff.

docs: v2.0.x: update multisig doc

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Closes #591 
I referred to the `CONTRIBUTING.md` in the `cosmos/cosmos-sdk` repo, but modified/simplified a lot.
The `CODE_OF_CONDUCT.md` is adopted from the [Contributor Covenant](https://www.contributor-covenant.org/).

docs: add `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`

---

.gitbook/validators/faq.md

As we've updated community tax from 0% to 2%.

docs: update community tax to 2%

---

.gitbook/5-oracles/1-operate-oracle-nodes/2-oracle-intialization.md

Based on #560, add oracle initialization document.
This document is quite duplicated with the [Initialize and run the oracle](https://github.com/medibloc/panacea-oracle/blob/main/docs/usage-init-run.md) which is located in panacea-oracle/README.md.
But, I added a details of the component in `config.toml`.

docs: add oracle initialization docs

---

go.mod
go.sum

In the previous PR #630, I forgot to use Informal System fork of Tendermint, as written in the Cosmos SDK [v0.45.12 changelog](https://github.com/cosmos/cosmos-sdk/blob/v0.45.13/CHANGELOG.md#v04512---2023-01-23) and as Gaia has [done](https://github.com/cosmos/gaia/blob/f9507c7e79f258aaa9a2265ca7d94e53988ffe16/go.mod#L303).

build(deps): use Informal System fork of Tendermint

---

.gitbook/0-about-panacea/1-data-exchange-protocol/2-How-DEP-works.md
.gitbook/3-protocol-devs/1-dep-specs/2-data-deal.md

Add a short description and usage examples of `json schema` and `presentation definition` in `Data Deal`.

docs: add data requirement description

---

x/pnft/client/cli/query_pnft.go

Close #680 
- typo fixed in query denom command

fix: typo query pnft command
