medibloc/panacea-core

- Jenkinsfile
- Makefile
- x/did/client/cli/query.go
- x/did/client/keystore/keystore.go
- x/did/client/keystore/keystore_test.go
- x/did/types/errors.go
> Call linter in CI

- docs/did.md
- x/did/alias.go
- x/did/client/cli/tx.go
- x/did/client/module_client.go
- x/did/handler.go
- x/did/keeper.go
- x/did/types/codec.go
- x/did/types/did.go
- x/did/types/msgs.go
Close #18 
TODO: 
- Use the keystore after merging #20
> Implement DID deletion

- cmd/panaceacli/main.go
- scripts/run_two_nodes_docker.sh
- x/did/client/cli/query.go
- x/did/client/module_client.go
- x/did/client/rest/query.go
- x/did/client/rest/rest.go
- x/did/querier.go
Close #17 
```
~ ❯❯❯ curl -X GET 127.0.0.1:1317/api/v1/did/did:panacea:testnet:LrDeegzUC2qtwQAP84nXo
{
"id": "did:panacea:testnet:LrDeegzUC2qtwQAP84nXo",
"publicKey": [
{
"id": "did:panacea:testnet:LrDeegzUC2qtwQAP84nXo#key1",
"type": "Secp256k1VerificationKey2018",
"publicKeyBase58": "pkSxxaWfJkMbBjNMPvADYmoqmCr2S7iuUfb7TqDYumCd"
}
],
"authentication": [
"did:panacea:testnet:LrDeegzUC2qtwQAP84nXo#key1"
]
}
```
> Add DID REST interface

- app/app.go
- app/export.go
- app/genesis.go
- x/did/client/cli/tx.go
- x/did/genesis.go
- x/did/genesis_keys.go
- x/did/handler.go
- x/did/keeper.go
- x/did/keeper_keys.go
- x/did/querier.go
- x/did/types/errors.go
- x/did/types/msgs.go
> Support genesis for DID

- x/did/types/did.go
- x/did/types/did_test.go
> Bug: wrong marshalling for signing: DID -> []byte

- x/did/client/cli/query.go
- x/did/client/cli/tx.go
- x/did/genesis.go
- x/did/genesis_keys_test.go
- x/did/genesis_test.go
- x/did/handler.go
- x/did/handler_test.go
- x/did/keeper.go
- x/did/querier.go
- x/did/types/auth.go
- x/did/types/auth_test.go
- x/did/types/did.go
- x/did/types/did_test.go
- x/did/types/errors.go
- x/did/types/msgs.go
> Prevent replay-attacks for DID operations

- x/did/client/keystore/keystore.go
- x/did/client/keystore/keystore_test.go
- x/did/client/keystore/testdata/web3.json
> Use PBKDF2 and SHA3Keccak256 for DID Keystore

- docs/did.md
- x/did/client/cli/tx.go
- x/did/client/cli/tx_test.go
- x/did/client/crypto/keystore_test.go
- x/did/genesis_keys_test.go
- x/did/genesis_test.go
- x/did/handler_test.go
- x/did/types/auth_test.go
- x/did/types/did.go
- x/did/types/did_test.go
- x/did/types/msgs_test.go
Close #56 
Please see the design decision at #56 .
If this PR is approved, I will modify SDKs.
> Simplify DID string spec: Remove the network ID and Use SHA256 instead of truncation

- .gitbook/specifications/aol.md
- x/aol/types/errors.go
- x/aol/types/msgs.go
- x/aol/types/msgs_test.go
> Enhance the AOL msg validation

- CHANGELOG.md
- x/aol/keeper/keeper.go
- x/aol/keeper/keeper_keys.go
- x/aol/keeper/keeper_keys_test.go
- x/did/keeper/keeper.go
- x/did/keeper/keeper_keys.go
> Fix parsing keeper keys of `x/aol` and `x/did`

- .gitbook/SUMMARY.md
- .gitbook/guide/interaction-with-the-network-cli.md
- .gitbook/specifications/did.md
- CHANGELOG.md
- client/lcd/swagger-ui/swagger.yaml
Baam! v1.3.2 introduced.
Close #74
> Release v1.3.2 + Update Swagger

- x/did/client/cli/tx.go
- x/did/client/cli/tx_test.go
- x/did/handler.go
- x/did/handler_test.go
- x/did/internal/secp256k1util/secp256k1util.go
- x/did/keeper/genesis_test.go
- x/did/types/did.go
- x/did/types/did_test.go
- x/did/types/errors.go
- x/did/types/msgs_test.go
Closes #96 
Core changes are in the `x/did/types/did.go`.
> feat: Support more key types for DID verification method

- .gitbook/resources/incentivized-testnet.md
> docs: Revise incentivized testnet guide

- .gitbook/SUMMARY.md
- .gitbook/resources/incentivized-testnet.md
based on https://www.notion.so/medibloc/Incentivized-Testnet-Plan-f95f2461a8884987974c54d18b0d10d5
Should be announced today 14:00 (Apr 28) with other SNS channels.
> docs: Incentivized Testnet

- .gitbook/guide/join-the-network.md
- .gitbook/resources/incentivized-testnet.md
will be announced to participants of the Incentivized Testnet.
> docs: Add 'panacea-opentestnet' URL to the Incentivized Testnet guide

- app/prefix.go
Use Panacea's HD Path.
TODO:
Migrate `x/*` logics
> stargate: Change HD Path

- app/app.go
- x/burn/alias.go
- x/burn/internal/keeper/burn.go
- x/burn/internal/keeper/burn_test.go
- x/burn/internal/keeper/genesis.go
- x/burn/internal/keeper/keeper.go
- x/burn/internal/types/codec.go
- x/burn/internal/types/expected_keepers.go
- x/burn/internal/types/genesis.go
- x/burn/internal/types/keys.go
- x/burn/module.go
A module has been added that deletes the coins when sent to the specified address.
- burn address : `panacea100000000000000000000000000000000nqmafp`
> Add burn coin modules

- .gitbook/resources/incentivized-testnet.md
> docs: Modify the timeline of Incentivized Testnet

- x/aol/types/topic.go
- x/aol/types/topic_test.go
There is a bug where the description is removed when add record and add/delete writer.
I fixed not removed description.
> fix: stargate: Fixed aol topic bug when change total count

- .github/workflows/docker-publish.yml
Reverts medibloc/panacea-core#189
> Revert "chore: Run docker-publish Github Actions only after the CI is completed"

- .gitbook/guide/installation.md
> docs: Add the `go get` guide with `replace` directives

- .gitbook/guide/join-the-network.md
- cmd/panacead/cmd/init.go
> refactor: Change blocks_per_year in init.go and timeout_commit in Gitbook

- .gitbook/guide/installation.md
- CHANGELOG.md
> docs: Release v2.0.2

- .gitbook/guide/cosmovisor.md
I wrote about how to install and apply the cosmovisor.
> docs: add how to use Cosmovisor to gitbook

- types/testsuite/suite.go
- x/market/client/cli/parse.go
- x/market/client/cli/tx.go
- x/market/client/cli/txDeal.go
- x/market/client/cli/txDeal_test.go
- x/market/keeper/deal.go
- x/market/keeper/deal_test.go
- x/market/keeper/msg_server_deal.go
- x/market/types/codec.go
- x/market/types/errors.go
- x/market/types/keys.go
- x/market/types/message_deal.go
> feat: Apply Signature Verification for SellData and Build Tx Command-line

- x/market/client/cli/parse.go
- x/market/client/cli/testdata/data_certificate_file.json
- x/market/client/cli/txDeal.go
- x/market/client/cli/txDeal_test.go
First of all, I just changed parsing method only in ```createDeal``` using ```jsonpb```.
If my work is correct, I will change method in ```sellData```.
> fix: Change parsing proto to json

- proto/panacea/market/v2/deal.proto
- x/market/genesis.go
- x/market/genesis_test.go
- x/market/keeper/deal.go
- x/market/keeper/deal_test.go
- x/market/types/deal.pb.go
- Add ```ListDeals``` and ```ListDataCertificates``` for genesis state.
- Test Code for ```ListDeals``` and ```ListDataCertificates``` in ```keeper/deal_test.go```.
- Add ```ExportGenesis``` in ```x/market/genesis.go```.
- Test Code for ```ExportGenesis``` in ```x/market/genesis_test.go```.
- ```GetDataCertificateListByDealId``` in next PR.
> feat: Add ListDeals and ListDataCertificates for Genesis State

- x/market/keeper/deal.go
- x/market/keeper/deal_test.go
Set deal status `COMPLETED` when deal's `cur_num_data` and `max_num_data` is equal.
> fix: Set Deal Status Completed

- proto/panacea/datapool/v2/query.proto
- x/datapool/client/cli/query.go
- x/datapool/client/cli/queryPool.go
- x/datapool/keeper/grpc_query_pool.go
- x/datapool/keeper/grpc_query_pool_test.go
- x/datapool/types/query.pb.go
- x/datapool/types/query.pb.gw.go
- Query for Registered Data Validator.
- This feature will be used in Off-chain Data Validator for checking duplication of validator.
> feat: Query for Registered Data Validator

- CHANGELOG.md
After this PR is merged to the `v2.0` branch, I will create a tag `v2.0.3` on that branch.
> docs: release v2.0.3

- .gitbook/overview/roadmap.md
pls review carefully since i wrote this PR on mobile. sorry about that
> docs: update roadmap: data market -> data exchange

- x/datapool/README.md
Update `README.md` according to the changes
- key of params
- addition of deposit rate
> docs: update params & deposit rate in README.md

- x/datapool/README.md
> docs: Fix DataPool Module Readme

- proto/panacea/datapool/v2/tx.proto
- x/datapool/client/cli/tx.go
- x/datapool/client/cli/txPool.go
- x/datapool/keeper/pool.go
- x/datapool/keeper/pool_test.go
- x/datapool/types/contract_msg.go
- x/datapool/types/tx.pb.go
- Rename remain `DataAccessNFT` to `DataPass`.
> refactor: Rename Data Access NFT to Data Pass

- x/datadeal/README.md
- x/datadeal/client/cli/parse.go
- Add README for `x/datadeal` module.
> docs: Add Data Deal README.MD

- x/oracle/keeper/oracle.go
- x/oracle/keeper/oracle_test.go
- x/oracle/types/errors.go
- Validate the update oracle requester's address is as same as existing oracle node's address
> feat: Validate Update Oracle Requester

- x/datadeal/client/cli/txDeal.go
- x/datadeal/keeper/deal.go
- x/datadeal/types/errors.go
- x/datadeal/types/message_deal.go
- x/datapool/keeper/pool.go
- x/datapool/types/errors.go
- x/datapool/types/message_pool.go
When creating deal/pool, at least 1 trusted oracle is required for data validation.
> fix: requirement of trusted oracles

- .gitbook/guide/installation.md
> chore: update installation.md

- go.mod
- go.sum
> fix: use a new version of `cosmos/ledger-go` for Ledger Nano S+

- CODEOWNERS
I fixed this because CodeOwner changed.
> docs: modify code owner

- x/oracle/keeper/oracle.go
Added logic to add to `OracleRegistrationQueue` when registering oracle.
> feat: add oracle registration to queue when register oracle

- cmd/panacead/cmd/genoracle.go
- cmd/panacead/cmd/root.go
- x/oracle/client/cli/tx.go
- x/oracle/client/cli/txRegisterOracleVote.go
- x/oracle/types/genesis.go
> feat: added CLI to vote for OracleRegistration and set oracle genesis

- cmd/panacead/cmd/genoracle.go
- x/oracle/client/cli/queryOracleRegistrationVote.go
I applied the changed specifications according to [this PR](https://github.com/medibloc/panacea-doracle/pull/34)
Also corrected the wrong cmd.
> feat: fix typo and change OraclePubKeyInfo's variable name

- x/oracle/types/message_oracle.go
I confirmed that an error occurred while MsgVoteOracleRegistration was executed, and implemented message_oracle.go.
> feat: implements the unimplemented part of MsgVoteOracleRegistration in the message_oracle.go

- app/types.go
hello, I think I found a typo while reading the code. If this is a typo, please merge it.
> fix: fixed typo in app/types.go

- x/oracle/keeper/oracle.go
- x/oracle/keeper/oracle_test.go
- x/oracle/keeper/upgrade_test.go
We need to implement to do different validation depending on oracleRegistrationType.
> fix: vote oracle registration validate

- cmd/panacead/cmd/genoracle.go
- go.sum
- x/datadeal/keeper/deal.go
- x/datadeal/keeper/deal_test.go
Closes #462 
- Add check `dataSale` status and enable reselling data if the sellerAddress equals.
- Passed in unit test.
> feat: add check seller address when SellData

- .gitbook/guide/join-the-network.md
This PR is a combination of commits in the `master` branch.
> docs: add state sync guide to v2.0.x doc

- cmd/panacead/cmd/genoracle.go
- x/oracle/types/oracle.go
> feat: add extra commission rate info to genoracle cmd

- proto/panacea/oracle/v2/oracle.proto
Related with https://github.com/medibloc/panacea-oracle/pull/55
> chore: add a comment for `trusted_block_*` fields in proto

- .gitbook/1-users/3-data-exchange/2-provide-data.md
Based on https://github.com/medibloc/panacea-core/pull/567, added user guide for providers.
> docs: add user guide for provider

- .gitbook/3-protocol-devs/1-dep-specs/4-data-validation.md
- .gitbook/3-protocol-devs/1-dep-specs/6-incentives.md
For now, our incentives (or reward distribution) is quite simple, so I just write down simply.
If you think some more contents are needed in this doc, please leave comments.
FYI, I intentionally did not write down the contents related to the oracle commission rate(plus max rate and max change rate). Because it seems more related to oracle.
> docs: incentives for protocol devs

- .gitbook/resources/validator-faq.md
Same as the PR #614, but based on the `release/v2.0.x` branch.
> docs: v2.0.x: update community tax to 2%

- .gitbook/5-oracles/1-operate-oracle-nodes/1-oracle-installation.md
`How about building from source?` part was written simply. If there is anything to add, please comment.
> docs: add oracle installation

- .gitbook/4-validators/3-join-mainnet-testnet.md
- .gitbook/5-oracles/1-operate-oracle-nodes/4-oracle-registration.md
If anyone feels it's too much or less as a guide to register oracle for oracle operator, I will make additional changes.
> docs: oracle-registration for oracle operators

- .gitbook/3-protocol-devs/1-dep-specs/5-confidential-oracle.md
Currently, both "Oracle Key Handshake" part and "Sealing Secrets and States" part do not clearly explain how these operations are happening. I think we should rewrite these two parts again to have a clear step by step guidance.
I completed grammar check up to Oracle Key.
> docs: update 5-confidential-oracle.md

- app/app.go
I just added a missed comment.
> chore: add comment to an upgrade handler for ibc-go v4

- .gitbook/4-validators/4-cosmovisor.md
Cosmovisor documentation needs updating, so I have made the following changes.
> docs: Update document of cosmovisor

- cmd/panacead/cmd/dep/hash_data.go
- cmd/panacead/cmd/dep/hash_json.go
- cmd/panacead/cmd/root.go
- go.mod
- go.sum
> feat: add a `panacead dep hash-data` command

- cmd/panacead/cmd/dep/decrypt_data.go
- cmd/panacead/cmd/dep/encrypt_data.go
- cmd/panacead/cmd/dep/hash_json.go
- cmd/panacead/cmd/dep/jwt.go
- cmd/panacead/cmd/root.go
- go.mod
- go.sum
Closes #652 
The `datahash` command will be implemented in derived branch based on this branch.
> refactor: add a `dep` command

- .gitbook/4-validators/3-join-mainnet-testnet.md
> docs: change state sync document

- x/pnft/keeper/denom.go
Fix: attempted update with `panacead tx pnft update-denom ...` did not change value of data
> bug: fixed not change data of denom when execute update command

- app/ante.go
- app/app.go
Close #686
- IBC ante handler was missing and added
> bug: Added not set to ibc ante handler

- .gitbook/guide/join-the-network.md
- Change node address about state sync
> docs: Changed node address about state sync

- .gitbook/guide/join-the-network.md
- Updated document about state sync node ip.
> docs: Updated state sync node ip
